import { Check, MapPin, RefreshCw, X } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../api/client.js';
import { DashboardPageHeader } from '../components/DashboardShell.jsx';
import { Spinner } from '../components/Spinner.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { useAuth } from '../context/AuthContext.jsx';

export function AdminLocationsPage(){const {token}=useAuth();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);try{setItems((await apiRequest('/localisations/suggestions',{token})).donnees||[])}catch(err){setError(err.message)}finally{setLoading(false)}},[token]);useEffect(()=>{
  // eslint-disable-next-line react-hooks/set-state-in-effect
  load();
},[load]);async function process(item,statut){await apiRequest(`/localisations/suggestions/${item.code_suggestion}`,{method:'PATCH',token,body:{statut}});load()}return <div><DashboardPageHeader title="Villes proposées" description="Examinez les villes absentes des listes géographiques." actions={<button className="secondary-action" onClick={load}><RefreshCw/>Actualiser</button>}/>{error&&<div className="alert alert--error">{error}</div>}<section className="app-panel management-panel">{loading?<div className="content-loading"><Spinner/>Chargement…</div>:items.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>Ville proposée</th><th>Province</th><th>Pays</th><th>Contact</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.code_suggestion}><td><strong><MapPin/> {item.ville_proposee}</strong><small className="cell-subtitle">{item.code_suggestion}</small></td><td>{item.province}</td><td>{item.pays}</td><td>{item.email_contact||item.nom_affichage||'—'}</td><td><StatusBadge status={item.statut}/></td><td>{item.statut==='EN_ATTENTE'&&<div className="table-actions"><button className="table-action table-action--success" onClick={()=>process(item,'ACCEPTEE')}><Check/></button><button className="table-action table-action--danger" onClick={()=>process(item,'REJETEE')}><X/></button></div>}</td></tr>)}</tbody></table></div>:<div className="management-empty"><MapPin/><h3>Aucune ville proposée</h3><p>Les signalements apparaîtront ici.</p></div>}</section></div>}
