import { ArrowLeft, BookOpen, Building2, Check, GitCompareArrows, MapPin, Plus, Users, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../api/client.js';
import { PageShell } from '../components/PageShell.jsx';
import { Spinner } from '../components/Spinner.jsx';

export function ComparePage(){const [all,setAll]=useState([]);const [codes,setCodes]=useState([]);const [data,setData]=useState([]);const [loading,setLoading]=useState(true);const [comparing,setComparing]=useState(false);const [error,setError]=useState('');useEffect(()=>{apiRequest('/universites').then(r=>{const list=(r.donnees||[]).filter(x=>x.statut_verification==='VERIFIEE');setAll(list);setCodes(list.slice(0,Math.min(3,list.length)).map(x=>x.code_universite))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);useEffect(()=>{
  if(codes.length<2){
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setData([]);return;
  }
  setComparing(true);
  apiRequest(`/universites/comparer?codes=${codes.join(',')}`).then(r=>setData(r.donnees||[])).catch(e=>setError(e.message)).finally(()=>setComparing(false))
},[codes]);function change(index,value){setCodes(current=>current.map((x,i)=>i===index?value:x))}return <PageShell><section className="compare-page"><div className="container"><Link className="back-link-public" to="/universites"><ArrowLeft/>Annuaire des universités</Link><div className="public-page-heading"><span className="eyebrow eyebrow--accent">Outil d’orientation</span><h1>Comparez les universités.</h1><p>Placez jusqu’à trois établissements côte à côte.</p></div>{error&&<div className="alert alert--error">{error}</div>}{loading?<div className="content-loading"><Spinner/>Chargement…</div>:<><div className="compare-selectors">{codes.map((code,index)=><label key={index}><span>Université {index+1}</span><select value={code} onChange={e=>change(index,e.target.value)}>{all.map(u=><option key={u.code_universite} value={u.code_universite} disabled={codes.includes(u.code_universite)&&u.code_universite!==code}>{u.nom}</option>)}</select>{codes.length>2&&<button onClick={()=>setCodes(v=>v.filter((_,i)=>i!==index))}><X/></button>}</label>)}{codes.length<3&&all.length>codes.length&&<button className="add-compare" onClick={()=>setCodes(v=>[...v,all.find(x=>!v.includes(x.code_universite)).code_universite])}><Plus/>Ajouter</button>}</div>{comparing?<div className="content-loading"><Spinner/>Comparaison…</div>:data.length>=2?<ComparisonTable data={data}/>:<div className="management-empty app-panel"><GitCompareArrows/><h3>Choisissez au moins deux universités</h3></div>}</>}</div></section></PageShell>}
function ComparisonTable({data}){const rows=[['Type',u=>u.type_universite==='PUBLIQUE'?'Publique':'Privée',Building2],['Localisation',u=>`${u.ville}, ${u.province}`,MapPin],['Frais annuels',u=>`${u.frais_minimum||0} – ${u.frais_maximum||0} USD`,BookOpen],['Filières',u=>u.nombre_filieres||0,BookOpen],['Étudiants',u=>u.nombre_etudiants||0,Users],['Inscriptions',u=>u.inscriptions_ouvertes?'Ouvertes':'Fermées',Check]];return <div className="comparison-table"><div className="comparison-row comparison-row--head"><div>Critères</div>{data.map(u=><div key={u.code_universite}><span><Building2/></span><strong>{u.sigle||u.nom}</strong><small>{u.nom}</small><Link to={`/universites/${u.code_universite}`}>Voir la fiche</Link></div>)}</div>{rows.map(([label,get,Icon])=><div className="comparison-row" key={label}><div><Icon/>{label}</div>{data.map(u=><div key={u.code_universite}><strong>{get(u)}</strong></div>)}</div>)}</div>}
