import { Building2, Check, Image, MapPin, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { apiRequest } from '../api/client.js';
import { DashboardPageHeader } from '../components/DashboardShell.jsx';
import { FileUploadField } from '../components/FileUploadField.jsx';
import { LocationSelector } from '../components/LocationSelector.jsx';
import { Spinner } from '../components/Spinner.jsx';
import { StatusBadge } from '../components/StatusBadge.jsx';
import { useAuth } from '../context/AuthContext.jsx';
import { useInstitution } from '../context/InstitutionContext.jsx';

const empty={nom:'',sigle:'',type:'PRIVEE',description:'',countryCode:'CD',pays:'Democratic Republic of the Congo',stateCode:'',ville:'',province:'',email:'',telephone:'',siteWeb:'',adresse:'',urlLogo:'',urlCouverture:'',inscriptionsOuvertes:false};

export function InstitutionProfilePage(){
  const {token,utilisateur}=useAuth(); const {universite,refresh}=useInstitution();
  const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{const source=universite||{};
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setForm({...empty,nom:source.nom||'',sigle:source.sigle||'',type:source.type_universite||'PRIVEE',description:source.description||'',pays:source.pays||utilisateur?.pays||empty.pays,ville:source.ville||utilisateur?.ville||'',province:source.province||utilisateur?.province||'',email:source.email||utilisateur?.email||'',telephone:source.telephone||'',siteWeb:source.site_web||'',adresse:source.adresse||'',urlLogo:source.url_logo||'',urlCouverture:source.url_couverture||'',inscriptionsOuvertes:Boolean(source.inscriptions_ouvertes)});
  },[universite,utilisateur]);
  function update(field){return event=>setForm(current=>({...current,[field]:event.target.type==='checkbox'?event.target.checked:event.target.value}))}
  async function submit(event){event.preventDefault();setSaving(true);setError('');setMessage('');try{if(!universite){await apiRequest('/universites',{method:'POST',token,body:{nom:form.nom,sigle:form.sigle||undefined,type:form.type,description:form.description||undefined,pays:form.pays,ville:form.ville,province:form.province,email:form.email||undefined,telephone:form.telephone||undefined,urlLogo:form.urlLogo||undefined,urlCouverture:form.urlCouverture||undefined}})}else{await apiRequest(`/universites/${universite.code_universite}`,{method:'PATCH',token,body:{nom:form.nom,sigle:form.sigle||null,description:form.description||null,pays:form.pays,ville:form.ville,province:form.province,email:form.email||null,telephone:form.telephone||null,siteWeb:form.siteWeb||null,adresse:form.adresse||null,urlLogo:form.urlLogo||null,urlCouverture:form.urlCouverture||null,inscriptionsOuvertes:form.inscriptionsOuvertes}})}await refresh();setMessage(universite?'Fiche mise à jour avec succès.':'Fiche créée et envoyée pour vérification.')}catch(err){setError(err.message)}finally{setSaving(false)}}
  return <div><DashboardPageHeader title={universite?'Fiche publique':'Créer la fiche universitaire'} description="L’identifiant URL est maintenant créé automatiquement." actions={universite&&<StatusBadge status={universite.statut_verification}/>}/>{message&&<div className="alert alert--success"><Check/>{message}</div>}{error&&<div className="alert alert--error">{error}</div>}<form className="profile-editor" onSubmit={submit}>
    <section className="app-panel profile-cover"><div className="profile-cover__image" style={form.urlCouverture?{backgroundImage:`url(${form.urlCouverture})`}:undefined}><Image/></div><div className="profile-logo">{form.urlLogo?<img src={form.urlLogo} alt="Logo"/>:<Building2/>}</div><div><h2>{form.nom||'Nom de l’université'}</h2><p><MapPin/>{form.ville||'Ville à choisir'}, {form.province||'Province'}</p></div></section>
    <section className="app-panel form-section"><div className="form-section__heading"><h2>Identité</h2><p>Nom officiel, sigle et présentation générale.</p></div><div className="form-grid"><Field label="Nom officiel"><input required minLength="3" value={form.nom} onChange={update('nom')}/></Field><Field label="Sigle"><input maxLength="20" value={form.sigle} onChange={update('sigle')}/></Field>{!universite&&<Field label="Type"><select value={form.type} onChange={update('type')}><option value="PUBLIQUE">Publique</option><option value="PRIVEE">Privée</option></select></Field>}<Field label="Présentation" wide><textarea rows="6" maxLength="5000" value={form.description} onChange={update('description')}/></Field></div></section>
    <section className="app-panel form-section"><div className="form-section__heading"><h2>Localisation</h2><p>Choisissez le pays, la province puis la ville.</p></div><LocationSelector value={form} emailContact={form.email} onChange={changes=>setForm(current=>({...current,...changes}))}/></section>
    <section className="app-panel form-section"><div className="form-section__heading"><h2>Coordonnées et médias</h2><p>Ajoutez le logo et la couverture directement depuis votre machine.</p></div><div className="form-grid"><Field label="E-mail public"><input type="email" value={form.email} onChange={update('email')}/></Field><Field label="Téléphone"><input value={form.telephone} onChange={update('telephone')}/></Field>{universite&&<><Field label="Site web"><input type="url" value={form.siteWeb} onChange={update('siteWeb')} placeholder="https://…"/></Field><Field label="Adresse"><input value={form.adresse} onChange={update('adresse')}/></Field></>}<div className="form-field--wide upload-grid"><FileUploadField label="Logo de l’université" value={form.urlLogo} token={token} onUploaded={url=>setForm(current=>({...current,urlLogo:url}))}/><FileUploadField label="Photo de couverture" value={form.urlCouverture} token={token} onUploaded={url=>setForm(current=>({...current,urlCouverture:url}))}/></div>{universite&&<label className="switch-field form-field--wide"><input type="checkbox" checked={form.inscriptionsOuvertes} onChange={update('inscriptionsOuvertes')}/><span/><div><strong>Inscriptions ouvertes</strong><small>Afficher que l’établissement accepte les candidatures.</small></div></label>}</div></section>
    <div className="form-save-bar"><p>Les modifications publiques peuvent être revérifiées.</p><button className="button" disabled={saving||!form.ville||!form.province}>{saving?<Spinner/>:<><Save/>Enregistrer</>}</button></div>
  </form></div>
}
function Field({label,wide,children}){return <label className={`editor-field ${wide?'form-field--wide':''}`}><span>{label}</span>{children}</label>}
