import { ArrowRight, BriefcaseBusiness, GraduationCap, Search, Sparkles, UserRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../api/client.js';
import { PageShell } from '../components/PageShell.jsx';
import { Spinner } from '../components/Spinner.jsx';

const portraits=['https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=500&q=85','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=85','https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=500&q=85'];
export function PortfoliosPage(){const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [error,setError]=useState('');useEffect(()=>{apiRequest('/profils?page=1&limite=50').then(r=>setItems(r.donnees||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const visible=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())),[items,search]);return <PageShell><section className="talent-hero"><div className="container"><div><span className="pill pill--light"><Sparkles/>Talents CampusHub</span><h1>Découvrez les talents formés dans nos universités.</h1><p>Compétences, projets et parcours académiques réunis au même endroit.</p></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Compétence, filière ou étudiant…"/></label></div></section><section className="section"><div className="container">{error&&<div className="alert alert--error">{error}</div>}{loading?<div className="content-loading"><Spinner/>Chargement…</div>:visible.length?<div className="talent-grid">{visible.map((p,i)=><article className="talent-card" key={p.code_profil}><div className="talent-card__photo">{p.url_photo_profil?<img src={p.url_photo_profil} alt={p.nom_affichage}/>:<img src={portraits[i%portraits.length]} alt="Portrait étudiant"/>}<span>Disponible</span></div><div><small>{p.code_profil}</small><h2>{p.nom_affichage}</h2><p className="talent-title">{p.titre_profil||'Talent étudiant'}</p><p><GraduationCap/>{p.nom_filiere} • {p.nom_universite}</p><div className="skill-list">{parseSkills(p.competences).slice(0,4).map(x=><span key={x}>{x}</span>)}</div><div className="talent-stats"><span><BriefcaseBusiness/>{p.nombre_publications||0} projets</span><span><UserRound/>{p.nombre_abonnes||0} abonnés</span></div><Link to={`/portfolios/${p.code_profil}`}>Voir le portfolio <ArrowRight/></Link></div></article>)}</div>:<div className="management-empty"><UserRound/><h3>Aucun talent trouvé</h3><p>Essayez une autre recherche.</p></div>}</div></section></PageShell>}
// eslint-disable-next-line react-refresh/only-export-components
export function parseSkills(value){if(Array.isArray(value))return value;try{return JSON.parse(value||'[]')}catch{return[]}}
