import { ArrowLeft, BookOpen, BriefcaseBusiness, Building2, GraduationCap, Mail, Sparkles, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiRequest } from '../api/client.js';
import { PageShell } from '../components/PageShell.jsx';
import { Spinner } from '../components/Spinner.jsx';
import { parseSkills } from './PortfoliosPage.jsx';

const photo='https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=85';
export function PortfolioDetailPage(){const {code}=useParams();const [profile,setProfile]=useState(null);const [publications,setPublications]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{apiRequest(`/profils/${code}`).then(async r=>{setProfile(r.donnees);const posts=await apiRequest(`/publications?auteur=${r.donnees.code_utilisateur}&page=1&limite=20`);setPublications(posts.donnees||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[code]);if(loading)return <PageShell><div className="full-loading"><Spinner/>Chargement du portfolio…</div></PageShell>;if(error||!profile)return <PageShell><div className="not-found"><UserRound/><h1>Profil introuvable</h1><p>{error}</p></div></PageShell>;return <PageShell><section className="portfolio-page"><div className="container"><Link className="back-link-public" to="/portfolios"><ArrowLeft/>Tous les talents</Link><section className="portfolio-profile"><img src={profile.url_photo_profil||photo} alt={profile.nom_affichage}/><div><span className="pill pill--teal"><Sparkles/>Talent CampusHub</span><h1>{profile.nom_affichage}</h1><h2>{profile.titre_profil||'Étudiant talentueux'}</h2><p><GraduationCap/>{profile.nom_universite} • {profile.nom_filiere}</p><div className="skill-list skill-list--large">{parseSkills(profile.competences).map(x=><span key={x}>{x}</span>)}</div><button className="button"><Mail/>Contacter</button></div></section><div className="portfolio-stats"><div><BriefcaseBusiness/><strong>{profile.nombre_publications||0}</strong><span>Projets</span></div><div><UserRound/><strong>{profile.nombre_abonnes||0}</strong><span>Abonnés</span></div><div><BookOpen/><strong>{profile.annee_diplomation||'—'}</strong><span>Diplomation</span></div></div><section className="portfolio-content"><div className="public-page-heading"><span className="eyebrow eyebrow--accent">Travaux sélectionnés</span><h2>Projets et publications</h2></div>{publications.length?<div className="portfolio-projects">{publications.map(p=><article key={p.code_publication}><span>{p.type_publication}</span><h3>{p.titre||'Projet étudiant'}</h3><p>{p.contenu}</p><small>{new Date(p.date_creation).toLocaleDateString('fr-FR')}</small></article>)}</div>:<div className="management-empty app-panel"><BriefcaseBusiness/><h3>Aucun projet publié</h3><p>Les prochains travaux apparaîtront ici.</p></div>}</section><section className="portfolio-academic app-panel"><span><Building2/></span><div><small>Parcours académique</small><h3>{profile.nom_filiere}</h3><p>{profile.nom_universite} • Promotion {profile.annee_diplomation||'en cours'}</p></div></section></div></section></PageShell>}
