import { Check, LockKeyhole, Save, ShieldCheck, UserRound } from 'lucide-react';
import { useState } from 'react';
import { apiRequest } from '../api/client.js';
import { DashboardPageHeader } from '../components/DashboardShell.jsx';
import { Spinner } from '../components/Spinner.jsx';
import { useAuth } from '../context/AuthContext.jsx';

export function SettingsPage(){const {utilisateur,token}=useAuth();const [form,setForm]=useState({nomAffichage:utilisateur?.nom_affichage||'',biographie:utilisateur?.biographie||'',ville:utilisateur?.ville||'',province:utilisateur?.province||'',urlPhotoProfil:utilisateur?.url_photo_profil||''});const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');async function submit(event){event.preventDefault();setSaving(true);setMessage('');setError('');try{await apiRequest('/utilisateurs/moi',{method:'PATCH',token,body:{...form,urlPhotoProfil:form.urlPhotoProfil||null,biographie:form.biographie||null}});setMessage('Informations du compte mises à jour.')}catch(err){setError(err.message)}finally{setSaving(false)}}return <div><DashboardPageHeader title="Paramètres" description="Préférences et sécurité de votre compte."/>{message&&<div className="alert alert--success"><Check/>{message}</div>}{error&&<div className="alert alert--error">{error}</div>}<form className="settings-grid" onSubmit={submit}><section className="app-panel settings-card settings-card--form"><span><UserRound/></span><div><h2>Informations du compte</h2><p>{utilisateur?.email} • {utilisateur?.code_utilisateur}</p></div><div className="form-grid form-field--wide"><Field label="Nom affiché"><input required value={form.nomAffichage} onChange={e=>setForm({...form,nomAffichage:e.target.value})}/></Field><Field label="Photo de profil (URL)"><input type="url" value={form.urlPhotoProfil} onChange={e=>setForm({...form,urlPhotoProfil:e.target.value})}/></Field><Field label="Ville"><input value={form.ville} onChange={e=>setForm({...form,ville:e.target.value})}/></Field><Field label="Province"><input value={form.province} onChange={e=>setForm({...form,province:e.target.value})}/></Field><Field label="Biographie" wide><textarea rows="4" value={form.biographie} onChange={e=>setForm({...form,biographie:e.target.value})}/></Field></div><button className="button" disabled={saving}>{saving?<Spinner/>:<><Save/>Enregistrer</>}</button></section><section className="app-panel settings-card"><span><LockKeyhole/></span><div><h2>Sécurité</h2><p>Le mot de passe est chiffré et n’est jamais affiché.</p><small>La modification du mot de passe sera disponible avec le module de récupération sécurisé.</small></div></section><section className="app-panel settings-card"><span><ShieldCheck/></span><div><h2>Statut du compte</h2><p>Rôle : {utilisateur?.role}</p><small>Vérification : {utilisateur?.statut_verification}</small></div></section></form></div>}
function Field({label,wide,children}){return <label className={`editor-field ${wide?'form-field--wide':''}`}><span>{label}</span>{children}</label>}
