import { ArrowRight, Check, GraduationCap, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../api/client.js';
import { LocationSelector } from '../components/LocationSelector.jsx';
import { PageShell } from '../components/PageShell.jsx';
import { Spinner } from '../components/Spinner.jsx';

export function StudentRegistrationPage() {
  const [form, setForm] = useState({ nomAffichage: '', email: '', motDePasse: '', pays: 'Democratic Republic of the Congo', province: '', ville: '', countryCode: 'CD', stateCode: '' });
  const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  async function submit(event) { event.preventDefault(); setLoading(true); setError(''); try { const body = { nomAffichage: form.nomAffichage, email: form.email, motDePasse: form.motDePasse, pays: form.pays, province: form.province, ville: form.ville, role: 'ETUDIANT' }; await apiRequest('/auth/inscription', { method: 'POST', body }); setDone(true); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  return <PageShell><section className="student-registration"><div className="registration-intro"><span><GraduationCap /></span><small>Rejoindre CampusHub</small><h1>Créez votre espace étudiant.</h1><p>Choisissez ensuite votre université et envoyez-lui une demande de confirmation.</p><ul><li><Check />Affiliation vérifiée par l’université</li><li><Check />Portfolio public et compétences</li><li><Check />Notifications de suivi</li></ul></div>{done ? <div className="registration-success"><Check /><h2>Votre compte est prêt</h2><p>Connectez-vous pour demander votre affiliation universitaire.</p><Link className="button" to="/connexion">Se connecter <ArrowRight /></Link></div> : <form className="form-card registration-form" onSubmit={submit}><h2>Informations personnelles</h2><p>La RDC est sélectionnée par défaut, mais tous les pays sont disponibles.</p>{error && <div className="alert alert--error">{error}</div>}<label className="form-field"><span>Nom complet</span><div className="input-with-icon"><UserRound /><input required minLength="2" value={form.nomAffichage} onChange={(e) => setForm({ ...form, nomAffichage: e.target.value })} /></div></label><label className="form-field"><span>Adresse e-mail</span><div className="input-with-icon"><Mail /><input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div></label><label className="form-field"><span>Mot de passe</span><div className="input-with-icon"><LockKeyhole /><input type="password" minLength="8" required value={form.motDePasse} onChange={(e) => setForm({ ...form, motDePasse: e.target.value })} /></div></label><LocationSelector value={form} emailContact={form.email} onChange={(values) => setForm((current) => ({ ...current, ...values }))} /><button className="button button--full button--large" disabled={loading || !form.province || !form.ville}>{loading ? <Spinner /> : <>Créer mon compte <ArrowRight /></>}</button><small className="form-help">Déjà inscrit ? <Link to="/connexion">Se connecter</Link></small></form>}</section></PageShell>;
}
