import { ArrowRight, Building2, GitCompareArrows, Search, SlidersHorizontal } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { apiRequest } from '../api/client.js';
import { PageShell } from '../components/PageShell.jsx';
import { Spinner } from '../components/Spinner.jsx';
import { UniversityCard } from '../components/UniversityCard.jsx';

export function UniversitiesPage(){const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filters,setFilters]=useState({search:'',ville:'',type:''});useEffect(()=>{apiRequest('/universites').then(r=>setItems((r.donnees||[]).filter(x=>x.statut_verification==='VERIFIEE'))).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const visible=useMemo(()=>items.filter(x=>(!filters.search||`${x.nom} ${x.sigle||''}`.toLowerCase().includes(filters.search.toLowerCase()))&&(!filters.ville||x.ville===filters.ville)&&(!filters.type||x.type_universite===filters.type)),[items,filters]);const villes=[...new Set(items.map(x=>x.ville))];return <PageShell><section className="directory-hero"><div className="container"><span className="eyebrow eyebrow--accent">Annuaire vérifié</span><h1>Trouvez votre future université.</h1><p>Comparez les filières, les frais et les services des établissements congolais.</p><div className="directory-search"><label><Search/><input value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})} placeholder="Nom ou sigle…"/></label><select value={filters.ville} onChange={e=>setFilters({...filters,ville:e.target.value})}><option value="">Toutes les villes</option>{villes.map(x=><option key={x}>{x}</option>)}</select><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">Tous les types</option><option value="PUBLIQUE">Publique</option><option value="PRIVEE">Privée</option></select></div></div></section><section className="section directory-section"><div className="container"><div className="directory-toolbar"><div><SlidersHorizontal/><span><strong>{visible.length}</strong> université(s) vérifiée(s)</span></div><Link className="secondary-action" to="/comparaison"><GitCompareArrows/>Comparer</Link></div>{error&&<div className="alert alert--error">{error}</div>}{loading?<div className="content-loading"><Spinner/>Chargement…</div>:visible.length?<div className="university-grid directory-grid">{visible.map((item,index)=><div key={item.code_universite}><UniversityCard university={item} index={index}/><Link className="card-overlay-link" to={`/universites/${item.code_universite}`}>Voir la fiche <ArrowRight/></Link></div>)}</div>:<div className="management-empty"><Building2/><h3>Aucun résultat</h3><p>Essayez avec d’autres critères.</p></div>}</div></section></PageShell>}
